site_name: Getting Started Guides

docs_dir: Docs

pages:
- ['index.md','Overview of mbed OS']
- ['installation.md', 'Quick Guide', 'Installation']
- ['FirstProjectmbedOS.md', 'Quick Guide', 'Your first application']
- ['Full_Guide/guide_index.md', 'Introduction to the mbed OS User Guide', 'Introduction']
- ['Full_Guide/app_on_yotta.md', 'Applications on mbed OS', 'mbed OS applications with yotta']
- ['Full_Guide/app_on_mbed_os.md', 'Applications on mbed OS', 'Writing applications for mbed OS']
- ['GetTheCode.md', 'Applications on mbed OS', 'Additional examples and code']
- ['Full_Guide/Debugging.md', 'mbed OS features', 'Debugging mbed OS applications']
- ['Full_Guide/mbed_tls.md', 'mbed OS features', 'Security with mbed TLS']
- ['Full_Guide/MINAR.md', 'mbed OS features', 'Asynchronous programming with MINAR']
- ['Full_Guide/memory.md', 'mbed OS features', 'Memory in mbed OS']
- ['Full_Guide/networking.md', 'mbed OS features', 'Networking in mbed OS']
- ['FurtherReading.md', 'Additional Resources', 'Further reading']
- ['Full_Guide/contributing.md', 'Additional Resources', 'Guidlines for code contributions']
- ['docker_install.md','','']
