site_name: Getting Started Guides

docs_dir: Docs

pages:
- ['index.md','Introduction']
- ['installation.md','Installation']
- ['FirstProjectmbedOS.md', 'Quick Guides', 'Your first application']
- ['Full_Guide/guide_index.md', 'mbed OS User Guide', 'Introduction to the mbed OS User Guide']
- ['Full_Guide/overview.md', 'mbed OS User Guide', 'Overview of mbed OS']
- ['Full_Guide/app_on_yotta.md', 'mbed OS User Guide', 'mbed OS applications with yotta']
- ['Full_Guide/app_on_mbed_os.md', 'mbed OS User Guide', 'Writing applications for mbed OS']
- ['FurtherReading.md', 'Additional Resources', 'Further reading']
- ['GetTheCode.md', 'Additional Resources', 'Get the code']
- ['docker_install.md','','']
