site_name: Getting Started Guides

docs_dir: Docs

pages:
- ['index.md','Introduction']
- ['GettingStartedmbedOS.md', 'Quick Guides', 'Getting started with mbed OS']
- ['FirstProjectmbedOS.md', 'Quick Guides', 'Your first application']
- ['/Full_Guide/guide_index.md', 'mbed OS User Guide', 'Introduction to the mbed OS User Guide']
- ['/Full_Guide/app_on_yotta.md.md', 'mbed OS User Guide', 'mbed OS applications with yotta']
- ['FurtherReading.md', 'Additional Resources', 'Further reading']
- ['GetTheCode.md', 'Additional Resources', 'Get the code']
